/*******************************************************************************/
/*  This file is auto-generated by Eclipse ThreadX GUIX Studio. Do not edit    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Eclipse ThreadX GUIX Studio application and re-generating the          */
/*  application resource file(s). For more information please refer to the     */
/*  Eclipse ThreadX GUIX Studio User Guide, or visit our web site at           */
/*  https://threadx.io                                                         */
/*                                                                             */
/*  GUIX Studio Revision 6.5.1.202602                                          */
/*  Date (dd.mm.yyyy): 13. 6.2026   Time (hh:mm): 17:15                        */
/*******************************************************************************/


#ifndef _UI_HOME_RESOURCES_H_
#define _UI_HOME_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define HOME 0
#define HOME_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define HOME_X_RESOLUTION 480
#define HOME_Y_RESOLUTION 272
#define HOME_THEME_CLASSIC 0
#define HOME_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define HOME_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define HOME_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define HOME_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define HOME_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define HOME_STRING_TABLE_SIZE 5

#endif                                       /* sentry                         */
