/*
 * Copyright 2019 ,2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: LPC54628J512
package_id: LPC54628J512ET180
mcu_data: ksdk2_0
processor_version: 9.0.0
board: LPCXpresso54628
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iocon.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B13, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI/CTIMER2_MAT3/SCT0_OUT8/TRACEDATA(2), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: A2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO0_30/FC0_TXD_SCL_MISO/CTIMER0_MAT0/SCT0_OUT9/TRACEDATA(1), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: P2, peripheral: SWD, signal: SWO, pin_signal: PIO0_10/FC6_SCK/CTIMER2_CAP2/CTIMER2_MAT0/FC1_TXD_SCL_MISO/SWO/ADC0_0, mode: inactive, invert: disabled,
    glitch_filter: disabled, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitPins(void)
{
    /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t SWO_TRGT = (/* Pin is configured as SWO */
                               IOCON_PIO_FUNC6 |
                               /* No addition pin function */
                               IOCON_PIO_MODE_INACT |
                               /* Input function is not inverted */
                               IOCON_PIO_INV_DI |
                               /* Enables digital function */
                               IOCON_PIO_DIGITAL_EN |
                               /* Input filter disabled */
                               IOCON_PIO_INPFILT_OFF |
                               /* Open drain is disabled */
                               IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN10 (coords: P2) is configured as SWO */
    IOCON_PinMuxSet(IOCON, BOARD_SWO_TRGT_PORT, BOARD_SWO_TRGT_PIN, SWO_TRGT);

    const uint32_t ISP_FC0_RXD = (/* Pin is configured as FC0_RXD_SDA_MOSI */
                                  IOCON_PIO_FUNC1 |
                                  /* No addition pin function */
                                  IOCON_PIO_MODE_INACT |
                                  /* Input function is not inverted */
                                  IOCON_PIO_INV_DI |
                                  /* Enables digital function */
                                  IOCON_PIO_DIGITAL_EN |
                                  /* Input filter disabled */
                                  IOCON_PIO_INPFILT_OFF |
                                  /* Standard mode, output slew rate control is enabled */
                                  IOCON_PIO_SLEW_STANDARD |
                                  /* Open drain is disabled */
                                  IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN29 (coords: B13) is configured as FC0_RXD_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, BOARD_ISP_FC0_RXD_PORT, BOARD_ISP_FC0_RXD_PIN, ISP_FC0_RXD);

    const uint32_t ISP_FC0_TXD = (/* Pin is configured as FC0_TXD_SCL_MISO */
                                  IOCON_PIO_FUNC1 |
                                  /* No addition pin function */
                                  IOCON_PIO_MODE_INACT |
                                  /* Input function is not inverted */
                                  IOCON_PIO_INV_DI |
                                  /* Enables digital function */
                                  IOCON_PIO_DIGITAL_EN |
                                  /* Input filter disabled */
                                  IOCON_PIO_INPFILT_OFF |
                                  /* Standard mode, output slew rate control is enabled */
                                  IOCON_PIO_SLEW_STANDARD |
                                  /* Open drain is disabled */
                                  IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, BOARD_ISP_FC0_TXD_PORT, BOARD_ISP_FC0_TXD_PIN, ISP_FC0_TXD);

    /* ---- LCD pin configuration ---- */
    const uint32_t lcd_pin_config = (IOCON_PIO_FUNC1 |
                                     IOCON_PIO_MODE_INACT |
                                     IOCON_PIO_INV_DI |
                                     IOCON_PIO_DIGITAL_EN |
                                     IOCON_PIO_INPFILT_OFF |
                                     IOCON_PIO_SLEW_STANDARD |
                                     IOCON_PIO_OPENDRAIN_DI);

    /* LCD control pins */
    IOCON_PinMuxSet(IOCON, 2U, 11U, lcd_pin_config);  /* LCD_PWR  */
    IOCON_PinMuxSet(IOCON, 2U, 13U, lcd_pin_config);  /* LCD_DCLK */
    IOCON_PinMuxSet(IOCON, 2U, 14U, lcd_pin_config);  /* LCD_FP   */
    IOCON_PinMuxSet(IOCON, 2U, 15U, lcd_pin_config);  /* LCD_AC   */
    IOCON_PinMuxSet(IOCON, 2U, 16U, lcd_pin_config);  /* LCD_LP   */

    /* LCD data pins VD3..VD7 */
    IOCON_PinMuxSet(IOCON, 2U, 21U, lcd_pin_config);  /* LCD_VD(3)  */
    IOCON_PinMuxSet(IOCON, 2U, 22U, lcd_pin_config);  /* LCD_VD(4)  */
    IOCON_PinMuxSet(IOCON, 2U, 23U, lcd_pin_config);  /* LCD_VD(5)  */
    IOCON_PinMuxSet(IOCON, 2U, 24U, lcd_pin_config);  /* LCD_VD(6)  */
    IOCON_PinMuxSet(IOCON, 2U, 25U, lcd_pin_config);  /* LCD_VD(7)  */

    /* LCD data pins VD10..VD15 */
    IOCON_PinMuxSet(IOCON, 2U, 28U, lcd_pin_config);  /* LCD_VD(10) */
    IOCON_PinMuxSet(IOCON, 2U, 29U, lcd_pin_config);  /* LCD_VD(11) */
    IOCON_PinMuxSet(IOCON, 2U, 30U, lcd_pin_config);  /* LCD_VD(12) */
    IOCON_PinMuxSet(IOCON, 2U, 31U, lcd_pin_config);  /* LCD_VD(13) */
    IOCON_PinMuxSet(IOCON, 3U, 0U,  lcd_pin_config);  /* LCD_VD(14) */
    IOCON_PinMuxSet(IOCON, 3U, 1U,  lcd_pin_config);  /* LCD_VD(15) */

    /* LCD data pins VD19..VD23 */
    IOCON_PinMuxSet(IOCON, 3U, 5U,  lcd_pin_config);  /* LCD_VD(19) */
    IOCON_PinMuxSet(IOCON, 3U, 6U,  lcd_pin_config);  /* LCD_VD(20) */
    IOCON_PinMuxSet(IOCON, 3U, 7U,  lcd_pin_config);  /* LCD_VD(21) */
    IOCON_PinMuxSet(IOCON, 3U, 8U,  lcd_pin_config);  /* LCD_VD(22) */
    IOCON_PinMuxSet(IOCON, 3U, 9U,  lcd_pin_config);  /* LCD_VD(23) */

    /* ---- EMC SDRAM pin configuration ---- */
    const uint32_t emc_pin_config = (IOCON_PIO_FUNC6 |
                                     IOCON_PIO_MODE_INACT |
                                     IOCON_PIO_INV_DI |
                                     IOCON_PIO_DIGITAL_EN |
                                     IOCON_PIO_INPFILT_OFF |
                                     IOCON_PIO_SLEW_FAST |
                                     IOCON_PIO_OPENDRAIN_DI);

    /* EMC data pins D0..D7 */
    IOCON_PinMuxSet(IOCON, 0U, 2U,  emc_pin_config);  /* EMC_D(0)  */
    IOCON_PinMuxSet(IOCON, 0U, 3U,  emc_pin_config);  /* EMC_D(1)  */
    IOCON_PinMuxSet(IOCON, 0U, 4U,  emc_pin_config);  /* EMC_D(2)  */
    IOCON_PinMuxSet(IOCON, 0U, 5U,  emc_pin_config);  /* EMC_D(3)  */
    IOCON_PinMuxSet(IOCON, 0U, 6U,  emc_pin_config);  /* EMC_D(4)  */
    IOCON_PinMuxSet(IOCON, 0U, 7U,  emc_pin_config);  /* EMC_D(5)  */
    IOCON_PinMuxSet(IOCON, 0U, 8U,  emc_pin_config);  /* EMC_D(6)  */
    IOCON_PinMuxSet(IOCON, 0U, 9U,  emc_pin_config);  /* EMC_D(7)  */

    /* EMC data pins D8..D15 */
    IOCON_PinMuxSet(IOCON, 1U, 19U, emc_pin_config);  /* EMC_D(8)  */
    IOCON_PinMuxSet(IOCON, 1U, 20U, emc_pin_config);  /* EMC_D(9)  */
    IOCON_PinMuxSet(IOCON, 1U, 21U, emc_pin_config);  /* EMC_D(10) */
    IOCON_PinMuxSet(IOCON, 1U, 4U,  emc_pin_config);  /* EMC_D(11) */
    IOCON_PinMuxSet(IOCON, 1U, 28U, emc_pin_config);  /* EMC_D(12) */
    IOCON_PinMuxSet(IOCON, 1U, 29U, emc_pin_config);  /* EMC_D(13) */
    IOCON_PinMuxSet(IOCON, 1U, 30U, emc_pin_config);  /* EMC_D(14) */
    IOCON_PinMuxSet(IOCON, 1U, 31U, emc_pin_config);  /* EMC_D(15) */

    /* EMC address pins A0..A9 */
    IOCON_PinMuxSet(IOCON, 0U, 18U, emc_pin_config);  /* EMC_A(0)  */
    IOCON_PinMuxSet(IOCON, 0U, 19U, emc_pin_config);  /* EMC_A(1)  */
    IOCON_PinMuxSet(IOCON, 0U, 20U, emc_pin_config);  /* EMC_A(2)  */
    IOCON_PinMuxSet(IOCON, 0U, 21U, emc_pin_config);  /* EMC_A(3)  */
    IOCON_PinMuxSet(IOCON, 1U, 5U,  emc_pin_config);  /* EMC_A(4)  */
    IOCON_PinMuxSet(IOCON, 1U, 6U,  emc_pin_config);  /* EMC_A(5)  */
    IOCON_PinMuxSet(IOCON, 1U, 7U,  emc_pin_config);  /* EMC_A(6)  */
    IOCON_PinMuxSet(IOCON, 1U, 8U,  emc_pin_config);  /* EMC_A(7)  */
    IOCON_PinMuxSet(IOCON, 1U, 26U, emc_pin_config);  /* EMC_A(8)  */
    IOCON_PinMuxSet(IOCON, 1U, 27U, emc_pin_config);  /* EMC_A(9)  */

    /* EMC address pins A10..A14 */
    IOCON_PinMuxSet(IOCON, 1U, 16U, emc_pin_config);  /* EMC_A(10) */
    IOCON_PinMuxSet(IOCON, 1U, 23U, emc_pin_config);  /* EMC_A(11) */
    IOCON_PinMuxSet(IOCON, 1U, 24U, emc_pin_config);  /* EMC_A(12) */
    IOCON_PinMuxSet(IOCON, 1U, 25U, emc_pin_config);  /* EMC_A(13) */
    IOCON_PinMuxSet(IOCON, 3U, 25U, emc_pin_config);  /* EMC_A(14) */

    /* EMC control pins */
    IOCON_PinMuxSet(IOCON, 0U, 15U, emc_pin_config);  /* EMC_WE    */
    IOCON_PinMuxSet(IOCON, 1U, 9U,  emc_pin_config);  /* EMC_CAS   */
    IOCON_PinMuxSet(IOCON, 1U, 10U, emc_pin_config);  /* EMC_RAS   */
    IOCON_PinMuxSet(IOCON, 1U, 11U, emc_pin_config);  /* EMC_CLK0  */
    IOCON_PinMuxSet(IOCON, 1U, 12U, emc_pin_config);  /* EMC_DYCS0 */
    IOCON_PinMuxSet(IOCON, 1U, 13U, emc_pin_config);  /* EMC_DQM0  */
    IOCON_PinMuxSet(IOCON, 1U, 14U, emc_pin_config);  /* EMC_DQM1  */
    IOCON_PinMuxSet(IOCON, 1U, 15U, emc_pin_config);  /* EMC_CKE0  */
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/

